spring.application.name=stories_live

# Load environment values bundled in the application resources.
spring.config.import=optional:classpath:.env[.properties]

# Postgres Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# MongoDB Database Configuration
spring.mongodb.uri=${MONGO_URI}
spring.mongodb.database=stories_live

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update