spring.application.name=stories_live

# Load environment values bundled in the application resources.
spring.config.import=optional:classpath:.env[.properties]

# Postgres Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# MongoDB Database Configuration
spring.mongodb.uri=${MONGO_URI}
spring.mongodb.database=stories_live

# Java Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update